# Java Properties
target_java_version=25

# Gradle Properties
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.vfs.watch=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.1.2
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Mod Properties
mod_version=2.2.1+26.1
target_minecraft_version=26.1
maven_group=thomilist
archives_base_name=dimensional-inventories

# Dependencies
fabric_api_version=0.148.2+26.1.2
gson_version=2.14.0
apache_commons_io_version=2.22.0
carpet_version=26.1

# Data pack format
data_pack_min_format=18
data_pack_max_format=101.1