name: build
on: [pull_request, push]

jobs:
  build:
    strategy:
      # To uncover platform-specific issues, do not fail fast
      fail-fast: false
      matrix:
        java: [
          #17, # <= 1.20.4
          21, # >= 1.20.5
        ]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Environment
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: 'microsoft'
      - name: Make Gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      # Build
      - name: Build
        run: ./gradlew build
      # Test
      - name: Run game tests
        run: ./gradlew runGametests
      - name: Display game test report
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          report_paths: '**/run/gametest/server/report/junit.xml'
      # Artifacts
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/
